name: TEST CI WORKFLOW

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:18.20.3
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password1
          POSTGRES_DB: garagepro_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: testPassword
      DB_NAME: garagepro_test
      DB_PORT: 5433
      DB_HOST: localhost
      CONTAINER_NAME: garagepro_test
      PORT: 3000
      JWT_TOKEN_SECRET: secret_test
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test
      - run: yarn test:e2e
